vim.pack.add({
	{ src = "https://github.com/tpope/vim-fugitive" },
	{ src = "https://github.com/tpope/vim-obsession" },
	{ src = "https://github.com/takac/vim-hardtime" },
	{ src = "https://github.com/lervag/vimtex" },
	{ src = "https://github.com/airblade/vim-gitgutter" },
	{ src = "https://github.com/neovim/nvim-lspconfig" },
	{ src = "https://github.com/hrsh7th/nvim-cmp" },
	{ src = "https://github.com/hrsh7th/cmp-nvim-lsp" },
	{ src = "https://github.com/j-hui/fidget.nvim" },
	{ src = "https://github.com/nvim-lualine/lualine.nvim" },
	{ src = "https://github.com/ibhagwan/fzf-lua", version = "main" },
	{ src = "https://codeberg.org/andyg/leap.nvim" },
	{ src = "https://github.com/stevearc/oil.nvim" },
	{ src = "https://github.com/stevearc/conform.nvim" },
	{ src = "https://github.com/catppuccin/nvim", name = "catppuccin" },
	{ src = "https://github.com/kdheepak/lazygit.nvim" },
	{ src = "https://github.com/iamcco/markdown-preview.nvim" },
}, { load = true, confirm = false })
