[font.offset]
x = 0
y = 1

[window]
decorations = "None"

[window.padding]
x = 0
y = 0

##markdown_url
##'\[[^]]*\]\(([^)]+)\)',
## url
##'(?:https?:##|git@|git://|ssh://|ftp://|file:///)\S+',
## diff_a
#'--- a/(\S+)',
## diff_b
#'\+\+\+ b/(\S+)',
## docker
#'sha256:([0-9a-f]{64})',
## path
#'(?:[.\w\-@~]+)?(?:/[.\w\-@]+)+',
## color
#'#[0-9a-fA-F]{6}',
## uuid
#'[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
## ipfs
#'Qm[0-9a-zA-Z]{44}',
## sha
#'[0-9a-f]{7,40}',
## ip
#'[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}',
## ipv6
#'[A-f0-9:]+:+[A-f0-9:]+[%\w[0-9]]+',
## address
#'0x[0-9a-fA-F]+',
## number
#'[0-9]{4,}',

[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
action="Copy"
hyperlinks = true
mouse.mods = "None"
persist = false
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+|sha256:([0-9a-f]{64})|#[0-9a-fA-F]{6}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|[0-9a-f]{7,40}|[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}|[A-f0-9:]+:+[A-f0-9:]+[%[A-Za-z0-9_][0-9]]+|0x[0-9a-fA-F]+|[0-9]{4,}"
