[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[terminal]
osc52 = "CopyPaste"

[font]
size = 10.0

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[window]
decorations = "None"
# important for tiling wm:
dynamic_padding = true

[window.padding]
x = 0
y = 0

# Default colors
[colors.primary]
background = '#282828'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#3c3836'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors
[colors.bright]
black   = '#3c3836'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

[keyboard]
bindings = [
{ key = "PageUp", mods = "None", action = "ScrollPageUp" },
{ key = "PageDown", mods = "None", action = "ScrollPageDown" },
{ key = "m", mods = "Control", action = "ScrollPageDown" },
{ key = ",", mods = "Control", action = "ScrollPageUp" },
{ key = "j", mods = "Control", action = "ScrollPageDown" },
{ key = "k", mods = "Control", action = "ScrollPageUp" },
{ key = ";", mods = "Control", action = "ToggleViMode" },
# Codes for tmux scrolling
{ key = "m", mods = "Alt", chars = "\uE000" },
{ key = ",", mods = "Alt", chars = "\uE001" },
{ key = "j", mods = "Alt", chars = "\uE002" },
{ key = "k", mods = "Alt", chars = "\uE003" },
{ key = ";", mods = "Alt", chars = "\uE004" },
]
##markdown_url
##'\[[^]]*\]\(([^)]+)\)',
## url
##'(?:https?:##|git@|git://|ssh://|ftp://|file:///)\S+',
## diff_a
#'--- a/(\S+)',
## diff_b
#'\+\+\+ b/(\S+)',
## docker
#'sha256:([0-9a-f]{64})',
## path
#'(?:[.\w\-@~]+)?(?:/[.\w\-@]+)+',
## color
#'#[0-9a-fA-F]{6}',
## uuid
#'[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
## ipfs
#'Qm[0-9a-zA-Z]{44}',
## sha
#'[0-9a-f]{7,40}',
## ip
#'[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}',
## ipv6
#'[A-f0-9:]+:+[A-f0-9:]+[%\w[0-9]]+',
## address
#'0x[0-9a-fA-F]+',
## number
#'[0-9]{4,}',

[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
action="Copy"
hyperlinks = true
mouse.mods = "None"
persist = false
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+|sha256:([0-9a-f]{64})|#[0-9a-fA-F]{6}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|[0-9a-f]{7,40}|[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}|[A-f0-9:]+:+[A-f0-9:]+[%[A-Za-z0-9_][0-9]]+|0x[0-9a-fA-F]+|[0-9]{4,}"
